#pragma once

namespace Windows
{
	enum WindowsColor
	{
		WC_SCROLLBAR,
		WC_BACKGROUND,
		WC_ACTIVECAPTION,
		WC_INACTIVECAPTION,
		WC_MENU,
		WC_WINDOW,
		WC_WINDOWFRAME,
		WC_MENUTEXT,
		WC_WINDOWTEXT,
		WC_CAPTIONTEXT,
		WC_ACTIVEBORDER,
		WC_INACTIVEBORDER,
		WC_APPWORKSPACE,
		WC_HIGHLIGHT,
		WC_HIGHLIGHTTEXT,
		WC_BTNFACE,
		WC_BTNSHADOW,
		WC_GRAYTEXT,
		WC_BTNTEXT,
		WC_INACTIVECAPTIONTEXT,
		WC_BTNHIGHLIGHT,

		WC_3DDKSHADOW,
		WC_3DLIGHT,
		WC_INFOTEXT,
		WC_INFOBK,

		WC_HOTLIGHT,
		WC_GRADIENTACTIVECAPTION,
		WC_GRADIENTINACTIVECAPTION,

		WC_MENUHILIGHT,
		WC_MENUBAR,

		WC_DESKTOP = WC_BACKGROUND,
		WC_3DFACE = WC_BTNFACE,
		WC_3DSHADOW = WC_BTNSHADOW,
		WC_3DHIGHLIGHT = WC_BTNHIGHLIGHT,
		WC_3DHILIGHT = WC_BTNHIGHLIGHT,
		WC_BTNHILIGHT = WC_BTNHIGHLIGHT,
	};
}