#pragma once

namespace Windows
{
	enum WindowNotification: unsigned __int16
	{
		WM_ACTIVATEAPP,
		WM_CANCELMODE,
		WM_CHILDACTIVATE,
		WM_CLOSE,
		WM_COMPACTING,
		WM_CREATE = 0x0001,
		WM_DESTROY = 0x0002,
		WM_DPICHANGED,
		WM_ENABLE,
		WM_ENTERSIZEMOVE,
		WM_EXITSIZEMOVE	,
		WM_GETICON,
		WM_GETMINMAXINFO,
		WM_INPUTLANGCHANGE,
		WM_INPUTLANGCHANGEREQUEST,
		WM_MOVE = 0x0003,
		WM_MOVING,
		WM_NCACTIVATE,
		WM_NCCALCSIZE,
		WM_NCCREATE,
		WM_NCDESTROY,
		WM_NULL = 0x0000,
		WM_QUERYDRAGICON,
		WM_QUERYOPEN,
		WM_QUIT,
		WM_SHOWWINDOW,
		WM_SIZE = 0x0005,
		WM_SIZING,
		WM_STYLECHANGED,
		WM_STYLECHANGING,
		WM_THEMECHANGED,
		WM_USERCHANGED,
		WM_WINDOWPOSCHANGED,
		WM_WINDOWPOSCHANGING,
	};
}